apiVersion: v1
kind: Service
metadata:
  name: lb-wordpress
  labels:
    app: wordpress
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
    - protocol: TCP
      name: http
      port: 5050
      targetPort: 5050
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050